### ISSUE TITLE
Setup a Google My Business profile

### ISSUE THREAD

**Issue by afterwire** [afterwire/moko#9]
**Problem:**
It can be kind of hard based just on your website for Google to figure out some key things about your business such as operating locations, hours, contact details etc. 

If we are able to setup a verified business listing with Google this is something that could potentially solve many problems for us at once and act as a great way for us to increase the visibility of the brand.

**Solution:**
- [x] Sign up for Google Business Listings [here](https://www.google.com/intl/sw_ke/business/)
- [x] You will have to verify your location(s) it would be good to do not only the factory location but the showrooms as well if possible

If we are able to get this far, there is a lot of other stuff we will be able to do from here in order to optimize the listing itself. But I don't want to overload you with information just yet in case it isn't possible :)

**Comment by AnneNyanchoka** [comment]
We already have a google my business page with two listings of the two showrooms that we have. One location is not verified because the options available are mail verification which we don't have. (The other listing was verified by phone number) 
Would you like me to add you as admin to see the listings? Optimization tactics would be great. We currently working on pushing content on page too.

**Comment by afterwire** [comment]
Yes if you could add me as an admin that would be great! Thank you!
